import math
import numpy as np

# Parametri za kamero
FRAME_WIDTH = 1280 #640
FRAME_HEIGHT = 720 #480
CAMERA_EXPOSURE = -8

# Parametri za detekcijo objektov
MAXIMUM_OBJECT_AREA = 1000
MINIMUM_OBJECT_AREA = 400
GRAYSCALE_THRESHOLD = 10

OFFSET_X = 0
OFFSET_Y = 0

# Prijem glede na center objekta
OFFSET_OBJ_X = -30
OFFSET_OBJ_Y = 3

ROBOT_IP = "192.168.64.55"
ROBOT = True

# calibration checkerboard
CHECKERBOARD = (10,7) #(9, 13)
CHECKERBOARD_SQUARE_SIZE = 25 #19.3

ORIGIN_COORD_FROM_CAM_X = 402 #141
ORIGIN_COORD_FROM_CAM_Y = 326 #208
# 406,48
X_COORD_OF_X_FROM_CAM = 647 #309
Y_COORD_OF_X_FROM_CAM = 154 #92

NUM_SQRT = 8

PIXEL_TO_MM = (NUM_SQRT * CHECKERBOARD_SQUARE_SIZE)/(math.sqrt((Y_COORD_OF_X_FROM_CAM - ORIGIN_COORD_FROM_CAM_Y) ** 2 + (ORIGIN_COORD_FROM_CAM_X-X_COORD_OF_X_FROM_CAM)**2))

# Parametri za izračun koordinat
ALPHA = 0 # math.atan((Y_COORD_OF_X_FROM_CAM - ORIGIN_COORD_FROM_CAM_Y) /
           #       (ORIGIN_COORD_FROM_CAM_X - X_COORD_OF_X_FROM_CAM))