import math

# Parametri za kamero
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
CAMERA_EXPOSURE = -8

# Parametri za detekcijo objektov
MAXIMUM_OBJECT_AREA = 500
MINIMUM_OBJECT_AREA = 100
GRAYSCALE_THRESHOLD = 10

# Transformacija v svetovne koordinate
PIXEL_TO_MM = 0.7614
ORIGIN_COORD_FROM_CAM_X = 160
ORIGIN_COORD_FROM_CAM_Y = 220
# 406,48
X_COORD_OF_X_FROM_CAM = 406
Y_COORD_OF_X_FROM_CAM = 48


ALPHA = 0.019997334
ALPHA = math.atan((Y_COORD_OF_X_FROM_CAM - ORIGIN_COORD_FROM_CAM_Y) /
                  (ORIGIN_COORD_FROM_CAM_X - X_COORD_OF_X_FROM_CAM))
print(math.degrees(ALPHA))
OFFSET_X = 0
OFFSET_Y = 0

# Prijem glede na center objekta
OFFSET_OBJ_X = -30
OFFSET_OBJ_Y = 3

ROBOT_IP = "192.168.64.55"
ROBOT = False
